services:
  omlx-exporter:
    container_name: "omlx-exporter"
    restart: "unless-stopped"
    build:
      context: .
      target: final
    env_file: .env
    ports:
      - 8001:8001

  prometheus:
    image: prom/prometheus:main
    container_name: "prometheus"
    restart: "unless-stopped"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - omlx-exporter

  grafana:
    image: grafana/grafana:main-slim
    container_name: "grafana"
    restart: "unless-stopped"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  prometheus-data:
