package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/txix-open/isp-kit/metrics"
)

var (
	statsTotalPromptTokens = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_total_prompt_tokens",
			Help: "Cumulative number of prompt tokens served by the server",
		}))
	statsTotalCompletionTokens = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_total_completion_tokens",
			Help: "Cumulative number of completion tokens generated by the server",
		}))
	statsTotalCachedTokens = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_total_cached_tokens",
			Help: "Cumulative number of tokens served from cache",
		}))
	statsTotalRequests = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_total_requests",
			Help: "Cumulative number of requests served by the server",
		}))
)

var (
	statsCacheEfficiency = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_cache_efficiency",
			Help: "Percentage of tokens served from cache (0-100)",
		}))
	statsAvgPrefillTPS = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_avg_prefill_tps",
			Help: "Average prefill tokens per second across all requests",
		}))
	statsAvgGenerationTPS = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_avg_generation_tps",
			Help: "Average generation tokens per second across all requests",
		}))
	statsUptimeSeconds = metrics.GetOrRegister(metrics.DefaultRegistry,
		prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "omlx_stats_uptime_seconds",
			Help: "Server uptime in seconds",
		}))
)

func UpdateStats(totalPromptTokens, totalCompletionTokens, totalCachedTokens, totalRequests float64) {
	statsTotalPromptTokens.Set(totalPromptTokens)
	statsTotalCompletionTokens.Set(totalCompletionTokens)
	statsTotalCachedTokens.Set(totalCachedTokens)
	statsTotalRequests.Set(totalRequests)
}

func UpdateGauges(cacheEfficiency, avgPrefillTPS, avgGenerationTPS, uptimeSeconds float64) {
	statsCacheEfficiency.Set(cacheEfficiency)
	statsAvgPrefillTPS.Set(avgPrefillTPS)
	statsAvgGenerationTPS.Set(avgGenerationTPS)
	statsUptimeSeconds.Set(uptimeSeconds)
}
